version: "2"

services:
  app:
    build: ./
    ports:
      - "8080:8080"
    links:
      - database
    volumes:
      - .:/usr/src/app
    depends_on:
      - database

  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: hungryhungry
